from rest_framework import routers
from . import views
from django.urls import path, include

# setting swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

schema_view = get_schema_view(
    openapi.Info(
        title="Tpower charge web API",
        default_version="v1.0.0",
        description="Tpower charge web API interaction documentation is automatically generated by Swagger",
    ),
    public=True,
)

router = routers.DefaultRouter()
# router.register('operators_info', views.User,'UserViewSet')
# router.register('get_charge_pile', views.charge_pile_viewSet,'charge_pile_viewSet')
router.register('charge_order', views.charge_order_viewSet,'charge_order_viewSet')
# router.register('car_info', views.car_info_viewSet,'car_info_viewSet')
# router.register('price_table', views.price_table_viewSet,'price_table_viewSet')
# router.register('charge_station_info', views.charge_station_info_viewSet, 'charge_station_info_viewSet')
# router.register('appuser_info', views.appuser_info_viewSet, 'appuser_info_viewSet')
# router.register('statement_info', views.statement_info_viewSet, 'statement_info_viewSet')
# router.register('price_type_info', views.price_type_info_viewSet, 'price_type_info_viewSet')
# router.register('vehicle',views.vehicle_viewSet,'vehicle_viewSet')
# router.register('operators_info_new',views.OperatorsInfoView,'OperatorsInfoView')
# router.register('nation_info',views.nation_info_viewSet,'nation_info_viewSet')
# router.register('dashboard info', views.dashboard_info_viewSet, 'dashboard_info_viewSet')

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('login/',views.LoginView.as_view(),name='login'),
    # path('logout/',views.LogoutView.as_view(),name='logout'),
    # path('dashboard_info/',views.DashboardView.as_view(),name='dashboard_info'),
    path('appuser-login/',views.apploginview.as_view(),name='appuser_login'),
    path('appuser-logout/',views.applogoutview.as_view(),name='appuser_logout'),
    path('sms/', views.SendSMSView.as_view(), name='sms'),
    path('verify/', views.VerifySMSView.as_view(), name='verify'),
    path('Register/', views.RegisterView.as_view(), name='Register'),
    path('pwd_update/', views.PwdUpdateView.as_view(), name='pwd_update'),
    path('user_info/', views.LoginInfoView.as_view(), name='uer_info'),
    path('card_info/', views.CardInfoView.as_view(), name='card_info'),
    path('start_ocpp/', views.StartOCPPView.as_view(), name='start_ocpp'),
    path('stop_ocpp/', views.StopOCPPView.as_view(), name='stop_ocpp'),
    path('data_info/', views.DataInfoView.as_view(), name='data_info'),
    path('charge_info/', views.ChargeInfoView.as_view(), name='charge_info'),
    path('card_delete/', views.CardInfoDelView.as_view(), name='card_delete'),
    path('card_update/', views.CardUpdateDelView.as_view(), name='card_update'),
    path('aus_states/',views.AusStatesInfoView.as_view(),name='aus_states'),
    path('pile_schedule/', views.PileScheduleView.as_view(), name='pile_schedule'),
    path('order_info/', views.GetOrderView.as_view(), name='order_info'),
    path('user_type/', views.UserTypeView.as_view(), name='user_type'),
    path('sucessful_pay/', views.SuccessfulPayView.as_view(), name='sucessful_pay'),
    path('ocpp_onmeter/', views.OCPPOnMeterView.as_view(), name='ocpp_onmeter'),
    path('create_charging/', views.CreateChargingView.as_view(), name='create_charging'),
    path('charging_check/', views.ChargingCheckView.as_view(), name='charging_check'),
    path('invoice/', views.InvoiceView.as_view(), name='invoice'),
    path('test/', views.TestView.as_view(), name='test'),
    # path('carbon_cal/', views.CarbonCaculate.as_view(), name='carbon_cal'),
    # path('statement_download/', views.statement_generate_pdf.as_view(), name='statement_download'),
    path('charge_pile/', views.get_charge_pile.as_view(),name='charge_pile'),
    # path('send_email/', views.SendEmailView.as_view(), name='send_email'),
    # #drf_yasg
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
