from rest_framework import routers
from . import views
from django.urls import path, include

# setting swagger
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

schema_view = get_schema_view(
    openapi.Info(
        title="Tpower charge web API",
        default_version="v1.0.0",
        description="Tpower charge web API interaction documentation is automatically generated by Swagger",
    ),
    public=True,
)

router = routers.DefaultRouter()
router.register('get_charge_pile', views.charge_pile_viewSet,'charge_pile_viewSet')
router.register('charge_order', views.charge_order_viewSet,'charge_order_viewSet')
router.register('car_info', views.car_info_viewSet,'car_info_viewSet')
router.register('price_table', views.price_table_viewSet,'price_table_viewSet')
router.register('charge_station_info', views.charge_station_info_viewSet, 'charge_station_info_viewSet')
router.register('appuser_info', views.appuser_info_viewSet, 'appuser_info_viewSet')
router.register('statement_info', views.statement_info_viewSet, 'statement_info_viewSet')
router.register('price_type_info', views.price_type_info_viewSet, 'price_type_info_viewSet')
router.register('vehicle',views.vehicle_viewSet,'vehicle_viewSet')
router.register('operators_info_new',views.OperatorsInfoView,'OperatorsInfoView')


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('dashboard_info/',views.DashboardView.as_view(),name='dashboard_info'),
    path('test/', views.TestView.as_view(), name='test'),
    # path('carbon_cal/', views.CarbonCaculate.as_view(), name='carbon_cal'),
    path('statement_download/', views.statement_generate_pdf.as_view(), name='statement_download'),
    path('start_ocpp/', views.StartOCPPView.as_view(), name='start_ocpp'),
    path('stop_ocpp/', views.StopOCPPView.as_view(), name='stop_ocpp'),
    path('data_info/', views.DataInfoView.as_view(), name='data_info'),
    path('charge_info/', views.ChargeInfoView.as_view(), name='charge_info'),
    path('aus_states/',views.AusStatesInfoView.as_view(),name='aus_states'),
    path('test/', views.TestView.as_view(), name='test'),
    path('statement_download/', views.statement_generate_pdf.as_view(), name='statement_download'),
    path('statement_url/',views.statement_PDF_URL.as_view(),name='statement_url'),
    path('teststatement/', views.TestStatement.as_view(), name="teststatement"),

    # #drf_yasg
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
