# Generated by Django 3.2.18 on 2023-04-19 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='appuser_info',
            fields=[
                ('appuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('appuser_username', models.CharField(blank=True, max_length=255, null=True)),
                ('appuser_firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('appuser_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('appuser_email', models.CharField(blank=True, max_length=255, null=True)),
                ('appuser_phone_no', models.IntegerField()),
                ('appuser_postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('appuser_isactive', models.CharField(max_length=255)),
                ('appuser_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('appuser_address', models.CharField(max_length=1800)),
                ('last_login', models.DateTimeField()),
                ('register_datetime', models.DateTimeField()),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='TOKEN')),
            ],
        ),
        migrations.CreateModel(
            name='charge_station_info',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('station_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('station_location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('station_postcode', models.CharField(max_length=255)),
                ('operators_id_fk', models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='price_type_info',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_type', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('veh_id', models.AutoField(primary_key=True, serialize=False)),
                ('veh_brand', models.CharField(max_length=255)),
                ('veh_model', models.CharField(max_length=255)),
                ('veh_charge_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='statement_info',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_datetime', models.DateTimeField()),
                ('statement_total_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('statement_charge_capacity', models.CharField(max_length=256)),
                ('operators_id_fk', models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='price_table',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_of_electricity', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_of_parking', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('set_datetime', models.DateTimeField()),
                ('station_id_fk', models.ForeignKey(blank=True, db_column='station_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.charge_station_info')),
            ],
        ),
        migrations.CreateModel(
            name='dashboard_info',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('appuser_id_fk', models.ForeignKey(blank=True, db_column='appuser_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.appuser_info')),
                ('operators_id_fk', models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='charge_pile',
            fields=[
                ('pile_id', models.AutoField(primary_key=True, serialize=False)),
                ('pile_charge_type', models.CharField(max_length=255)),
                ('pile_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pile_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pile_model', models.CharField(max_length=255)),
                ('pile_location_state', models.CharField(blank=True, choices=[('vic', 'VIC'), ('nsw', 'NSW'), ('tas', 'TAS'), ('qld', 'QLD'), ('wa', 'WA'), ('nt', 'NT'), ('act', 'ACT')], max_length=255, null=True)),
                ('pile_status', models.CharField(blank=True, choices=[('Available', 'available'), ('Unavailable', 'unavailable'), ('Breakdown', 'breakdown'), ('Disconnect', 'disconnect')], max_length=255, null=True)),
                ('pile_sn', models.CharField(max_length=255)),
                ('pile_vendor', models.CharField(max_length=255)),
                ('pile_metrfirmwareversion', models.CharField(max_length=255)),
                ('pile_ratekw', models.CharField(max_length=255)),
                ('pile_connect_no', models.IntegerField()),
                ('pile_outputcurrentmax', models.CharField(max_length=255)),
                ('station_id_fk', models.ForeignKey(blank=True, db_column='station_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.charge_station_info')),
            ],
        ),
        migrations.CreateModel(
            name='charge_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_start_datetime', models.DateTimeField()),
                ('order_end_datetime', models.DateTimeField()),
                ('order_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST', models.FloatField(default=1)),
                ('appuser_id_fk', models.ForeignKey(blank=True, db_column='appuser_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.appuser_info')),
                ('operators_id_fk', models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pile_id_fk', models.ForeignKey(blank=True, db_column='pile_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.charge_pile')),
            ],
        ),
        migrations.CreateModel(
            name='charge_info',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('current', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('charge_capacity', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('meter_value', models.TextField()),
                ('transaction_id', models.BigIntegerField(blank=True)),
                ('id_tag', models.CharField(default='', max_length=255)),
                ('charge_pile_id', models.ForeignKey(blank=True, db_column='charge_pile_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.charge_pile')),
            ],
        ),
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_registration_no', models.CharField(max_length=256)),
                ('register_datetime', models.DateTimeField()),
                ('appuser_id_fk', models.ForeignKey(blank=True, db_column='appuser_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.appuser_info')),
                ('veh_id_fk', models.ForeignKey(blank=True, db_column='veh_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.vehicle')),
            ],
        ),
    ]
