# Generated by Django 3.2.18 on 2023-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230421_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='nation_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nation', models.CharField(blank=True, max_length=255, null=True)),
                ('nation_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
