# Generated by Django 4.0.4 on 2023-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache',
            old_name='key',
            new_name='cache_key',
        ),
    ]
