# Generated by Django 4.0.4 on 2023-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_key_cache_cache_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_address',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_isactive',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_phone_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='appuser_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
