# Generated by Django 4.2 on 2023-05-08 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_appuser_info_appuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser_info',
            name='card_id_fk',
            field=models.ForeignKey(blank=True, db_column='card_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.card_info'),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 10, 8, 0, 826171), null=True),
        ),
    ]
