# Generated by Django 4.2 on 2023-05-08 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_appuser_info_card_id_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser_info',
            name='card_id_fk',
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 10, 27, 28, 494955), null=True),
        ),
    ]
