# Generated by Django 4.2 on 2023-05-08 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_appuser_info_card_id_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_info',
            old_name='expire_date',
            new_name='card_vendor',
        ),
        migrations.AddField(
            model_name='card_info',
            name='expire_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card_info',
            name='expire_date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 14, 11, 39, 244790), null=True),
        ),
    ]
