# Generated by Django 4.2 on 2023-05-09 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_expire_date_card_info_card_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_info',
            name='connect_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 9, 16, 1, 38, 597792), null=True),
        ),
        migrations.AlterField(
            model_name='card_info',
            name='card_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
