# Generated by Django 4.2 on 2023-05-09 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_charge_info_connect_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge_info',
            old_name='connect_id',
            new_name='connector_id',
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 9, 16, 21, 45, 767063), null=True),
        ),
    ]
