# Generated by Django 4.2 on 2023-05-10 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_connect_id_charge_info_connector_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_info',
            name='appuser_id_fk',
            field=models.ForeignKey(blank=True, db_column='appuser_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.appuser_info'),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 10, 15, 3, 40, 219362), null=True),
        ),
    ]
