# Generated by Django 4.0.5 on 2023-05-12 04:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_charge_info_appuser_id_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 4, 36, 26, 461075), null=True),
        ),
        migrations.CreateModel(
            name='operators_info',
            fields=[
                ('operators_id', models.AutoField(primary_key=True, serialize=False)),
                ('operators_postcode', models.CharField(blank=True, max_length=256, null=True)),
                ('operators_state', models.CharField(blank=True, max_length=256, null=True)),
                ('operators_id_fk', models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
