# Generated by Django 4.0.4 on 2023-05-12 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_appuser_info_register_datetime_operators_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser_info',
            name='card_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 21, 32, 1, 344616), null=True),
        ),
    ]
