# Generated by Django 4.0.4 on 2023-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_appuser_info_card_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser_info',
            name='register_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
