# Generated by Django 4.1.1 on 2023-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_appuser_info_register_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_order',
            name='GST',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
    ]
