# Generated by Django 4.1.1 on 2023-05-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_charge_order_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_order',
            name='GST',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='charge_pile',
            name='pile_location_state',
            field=models.CharField(blank=True, choices=[('vic', 'VIC'), ('nsw', 'NSW'), ('tas', 'TAS'), ('qld', 'QLD'), ('wa', 'WA'), ('nt', 'NT'), ('act', 'ACT'), ('sa', 'SA')], max_length=255, null=True),
        ),
    ]
