# Generated by Django 4.1.1 on 2023-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_charge_order_gst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pile_schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekly', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
