# Generated by Django 4.1.1 on 2023-05-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_pile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile_schedule',
            name='charge_pile_fk',
            field=models.ForeignKey(blank=True, db_column='charge_pile_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.charge_pile'),
        ),
    ]
