# Generated by Django 4.1.1 on 2023-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_pile_schedule_charge_pile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_pile',
            name='charge_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
