# Generated by Django 4.1.1 on 2023-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_charge_pile_charge_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_order',
            name='order_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='GST',
            field=models.FloatField(blank=True, default=0.1),
        ),
    ]
