# Generated by Django 4.1.1 on 2023-05-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_charge_order_order_status_alter_charge_order_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_order',
            name='order_status',
            field=models.CharField(blank=True, default='unpaid', max_length=255, null=True),
        ),
    ]
