# Generated by Django 4.1.1 on 2023-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_charge_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_order',
            name='GST',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='charge_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='order_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='order_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='order_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
