# Generated by Django 4.0.4 on 2023-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_charge_order_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='card_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
