# Generated by Django 4.0.4 on 2023-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_card_info_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='user_card_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
