# Generated by Django 4.0.4 on 2023-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_card_info_user_card_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_info',
            old_name='card_name',
            new_name='card_first_name',
        ),
        migrations.AddField(
            model_name='card_info',
            name='card_country',
            field=models.CharField(blank=True, default='Australia', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='card_info',
            name='card_last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
