# Generated by Django 4.0.4 on 2023-05-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_rename_card_name_card_info_card_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_info',
            old_name='security_code',
            new_name='card_CVC',
        ),
    ]
