# Generated by Django 4.1.1 on 2023-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_rename_security_code_card_info_card_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_order',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
