# Generated by Django 4.1.1 on 2023-05-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_charge_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_order',
            name='paid_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
