# Generated by Django 4.1.1 on 2023-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_charge_order_paid_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_order',
            name='paid_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charge_order',
            name='paid_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
