# Generated by Django 4.1.1 on 2023-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_charge_order_paid_token_alter_charge_order_paid_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_pile',
            name='pile_addres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
