# Generated by Django 4.1.1 on 2023-05-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_charge_pile_pile_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operators_info',
            old_name='operators_id_fk',
            new_name='user_id_fk',
        ),
    ]
