# Generated by Django 4.1.1 on 2023-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_rename_operators_id_fk_operators_info_user_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser_info',
            name='user_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
