# Generated by Django 3.2.14 on 2023-08-29 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0038_alter_operators_info_user_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_pile',
            name='operators_id_fk',
            field=models.ForeignKey(blank=True, db_column='user_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charge_pile',
            name='pile_status',
            field=models.CharField(blank=True, choices=[('Available', 'available'), ('Unavailable', 'unavailable'), ('Charging', 'charging')], max_length=255, null=True),
        ),
    ]
