# Generated by Django 3.2.14 on 2023-08-29 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0039_auto_20230829_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_pile',
            name='operators_id_fk',
            field=models.ForeignKey(blank=True, db_column='operators_id_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
